parser: babel-eslint

plugins:
  - flowtype

extends:
  - airbnb-base
  - plugin:prettier/recommended

env:
  node: true
  browser: false

rules:
  prettier/prettier: error

  no-use-before-define: off
  consistent-return: off
  no-return-assign: off
  no-param-reassign: off
  no-redeclare: off
  eqeqeq:
    - error
    - smart

  import/prefer-default-export: off

  flowtype/define-flow-type: error
  flowtype/no-dupe-keys: off
  flowtype/no-mutable-array: error
  flowtype/no-primitive-constructor-types: error
  flowtype/no-types-missing-file-annotation: error
  flowtype/require-valid-file-annotation:
    - error
    - never
    - annotationStyle: block
  flowtype/type-id-match:
    - error
    - '^[A-Z][a-z0-9]*'
  flowtype/use-flow-type: error
